version: '3'

services:

  kibana:
    image: jahrik/arm-kibana:arm32v7
    environment:
      ELASTICSEARCH_URL: "${ELASTICSEARCH_URL}"
    ports:
      - 5601:5601
    # volumes:
      # - /mnt/g2/kibana:/data:rw
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm32v7
