---
services:

  kibana:
    image: jahrik/arm-kibana:latest
    environment:
      ELASTICSEARCH_HOSTS: "${ELASTICSEARCH_HOSTS:-http://elasticsearch:9200}"
    networks:
      - traefik
      - elk
    deploy:
      labels:
        traefik.enable: 1
        traefik.backend: kibana
        traefik.docker.network: traefik
        traefik.port: 5601
        traefik.frontend.rule: Host:kibana.homelab.business

networks:
  traefik:
    driver: overlay
    external: true
  elk:
    driver: overlay
    external: true
