version: '3'

services:

  kibana:
    image: jahrik/arm-kibana:arm32v7
    environment:
      ELASTICSEARCH_URL: "${ELASTICSEARCH_URL}"
    networks:
      - traefik
      - elk
    deploy:
      labels:
        traefik.enable: 1
        traefik.backend: kibana
        traefik.docker.network: traefik
        traefik.port: 5601
        traefik.frontend.rule: Host:kibana.homelab.business
      placement:
        constraints:
          - node.labels.arch == aarch64

networks:
  traefik:
    driver: overlay
    external: true
  elk:
    driver: overlay
    external: true
