---
- hosts: aarch64
  become: true
  become_method: sudo
  tasks:
    - name: Create persistent data dir
      file:
        path: /mnt/g1/kibana
        state: directory
        owner: 999
        group: 999
        mode: 0755
